# Day 6: Session 6C - A Date Is Not a Number

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/6c_dates.html)

Date: 09/08/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/toolik_weather.csv'
toolik = pd.read_csv(url)

toolik[['Year', 'Month', 'Date', 'Daily_AirTemp_Mean_C']].head()

   Year  Month      Date  Daily_AirTemp_Mean_C
0  1988      6  19880601                   8.4
1  1988      6  19880602                   6.0
2  1988      6  19880603                   5.8
3  1988      6  19880604                   1.8
4  1988      6  19880605                   6.8

In [ ]:
# so what even is the type of a date column?
toolik['Date'].dtype

# so basically its an integer and its some giant unhelpful number
# but we can use certain functions to make it work nice
toolik['date'] = pd.to_datetime(toolik['Date'], format='%Y%m%d')

toolik[['Date', 'date']].head()
# now the type of date column is datetime64

       Date       date
0  19880601 1988-06-01
1  19880602 1988-06-02
2  19880603 1988-06-03
3  19880604 1988-06-04
4  19880605 1988-06-05

In [4]:
# lets go ahead and look at the first and last date in the data
print(toolik['date'].dtype)
print(toolik['date'].min())
print(toolik['date'].max())

datetime64[ns]
1988-06-01 00:00:00
2018-12-31 00:00:00

In [7]:
# you can pull a the month, day or year out of a date string using the 
# following commands
toolik['year'] = toolik['date'].dt.year
toolik['month'] = toolik['date'].dt.month
toolik['day'] = toolik['date'].dt.day

toolik[['date', 'year', 'month', 'day']].head()

#adding a day of year column
toolik['dayyear'] = toolik['date'].dt.dayofyear
toolik['dayyear']

0        153
1        154
2        155
3        156
4        157
        ...
11166    361
11167    362
11168    363
11169    364
11170    365
Name: dayyear, Length: 11171, dtype: int32

In [9]:
# now it is easy to find sum stats by month or day or etc
toolik.groupby('month')['Daily_AirTemp_Mean_C'].mean().round(2)

# and its a good idea to run the mean with a count stat at the same time
toolik.groupby('year')['Daily_AirTemp_Mean_C'].agg(['count', 'mean']).head(3).round(2)

      count  mean
year
1988    214 -4.88
1989    365 -7.94
1990    365 -8.54

In [14]:
# now lets do an analysis if the arctic is actually getting colder
# as the years pass
early = toolik[toolik['year'] <= 1998]
late = toolik[toolik['year'] >= 2009]

# first we create two dataframes, one of the first 11 years of data and
# one of the last 11 years of data

comparison = pd.DataFrame({
    'early': early.groupby('month')['Daily_AirTemp_Mean_C'].mean(),
    'late': late.groupby('month')['Daily_AirTemp_Mean_C'].mean(),
})

comparison['change'] = comparison['late'] - comparison['early']

comparison.round(2)
#then we add both grouped data frames to a bigger df, and create a column that compares 
# the monthly mean of each group early and late

print(comparison['change'].mean())

0.7436935605194014