# Day 3 EOD: The Banana Index

Date: 09/02/2026

In [ ]:
import pandas as pd
url = 'https://github.com/TheEconomist/banana-index-data/releases/download/1.0/bananaindex.csv'
data = pd.read_csv(url, index_col = 'entity')

In [8]:
bad = ['year', 'Banana values', 'type', 'Chart?', 'Unnamed: 16']
data = data.drop(bad, axis = 'columns')

In [22]:
data.shape
data.head()
data.info()


data.loc['Bananas', 'Bananas index (kg)']

<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, Ale to Yoghurt
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   emissions_kg                       160 non-null    float64
 1   emissions_1000kcal                 160 non-null    float64
 2   emissions_100g_protein             158 non-null    float64
 3   emissions_100g_fat                 160 non-null    float64
 4   land_use_kg                        160 non-null    float64
 5   land_use_1000kcal                  160 non-null    float64
 6   Land use per 100 grams of protein  158 non-null    float64
 7   Land use per 100 grams of fat      160 non-null    float64
 8   Bananas index (kg)                 160 non-null    float64
 9   Bananas index (1000 kcalories)     160 non-null    float64
 10  Bananas index (100g protein)       160 non-null    float64
dtypes: float64(11)
memory usage: 19.1+ KB

1.0

In [25]:
data.sort_values('Bananas index (kg)', ascending = False)
data.sort_values('Bananas index (1000 kcalories)', ascending = False)
data.sort_values('Bananas index (100g protein)', ascending = False)

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Coconut milk,3.319990,12.848692,257.293857,28.268731,0.545269,2.216621,32.738749,4.415864,3.801444,14.670763,33.320155
Sugar,1.851686,0.464977,159.733044,239.244524,2.153669,0.539469,198.893081,293.640795,2.120211,0.530915,20.685802
Grapes,8.278876,12.671419,116.820455,203.724449,1.536532,2.349845,21.639156,37.785507,9.479453,14.468351,15.128521
Beef steak,129.747715,68.095953,64.190391,146.107870,427.331126,223.690135,211.381205,478.803717,148.563324,77.752629,8.312805
Raspberries,8.370972,24.614978,60.839171,186.986093,1.544836,4.542864,11.227628,34.509046,9.584904,28.105624,7.878815
...,...,...,...,...,...,...,...,...,...,...,...
Pumpkin seeds,1.323975,0.317773,0.559060,0.455242,3.336552,0.816564,1.395185,1.190146,1.515974,0.362836,0.072400
Almonds,0.602368,0.105029,0.328335,0.119361,8.230927,1.423376,4.261040,1.610136,0.689721,0.119923,0.042520
Almond butter,0.387011,0.067265,0.207599,0.079103,7.683045,1.296870,3.608433,1.495297,0.443134,0.076804,0.026885
Sunflower oil,3.661397,0.424541,NaN,0.375294,19.461267,2.257053,NaN,1.995235,4.192362,0.484745,0.000000
Olive oil,5.184628,0.591959,NaN,0.523292,21.707958,2.478318,NaN,2.190833,5.936487,0.675905,0.000000

In [37]:
data['Bananas index (kg)'] > 10
data[data['Bananas index (kg)'] > 10].shape
data[~(data['Bananas index (kg)'] > 1)].shape
data[~(data['Bananas index (kg)'] > 1)]

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Ale,0.488690,0.317338,0.878525,2.424209,0.811485,0.601152,1.577687,3.065766,0.559558,0.362340,0.113771
Almond butter,0.387011,0.067265,0.207599,0.079103,7.683045,1.296870,3.608433,1.495297,0.443134,0.076804,0.026885
Almond milk,0.655888,2.222230,13.595512,4.057470,1.370106,2.675063,12.687839,4.600530,0.751002,2.537364,1.760651
Almonds,0.602368,0.105029,0.328335,0.119361,8.230927,1.423376,4.261040,1.610136,0.689721,0.119923,0.042520
Apple juice,0.458378,0.955184,29.152212,19.754980,0.660629,1.382839,43.232158,26.246743,0.524851,1.090638,3.775280
Apples,0.507354,0.898188,13.442716,25.594410,0.668999,1.205081,18.667990,36.386277,0.580929,1.025560,1.740863
Bagels,0.802813,0.329389,0.959624,3.741236,2.262947,0.924206,2.663544,10.173081,0.919234,0.376100,0.124274
Bananas,0.873350,0.875803,7.721869,20.469220,2.639824,2.717877,22.821229,64.907342,1.000000,1.000000,1.000000
Beer,0.686283,0.606472,1.509246,4.455620,0.827887,0.766329,2.069713,4.625173,0.785806,0.692475,0.195451
Coconut oil,0.528741,0.339007,9.821966,4.106947,0.734497,0.427187,14.175496,4.570065,0.605418,0.387081,1.271967
Courgettes,0.846479,3.254015,4.499813,16.354527,1.267480,4.761213,6.560221,24.104361,0.969233,3.715466,0.582736
Cucumber,0.847114,4.115565,7.338882,22.657421,1.080249,5.391894,9.537909,29.531063,0.969960,4.699193,0.950402
Frozen chips (french fries),0.753472,0.531024,3.822119,3.244333,2.105977,1.455530,10.762102,8.036323,0.862738,0.606329,0.494973
Frozen onion rings,0.771175,0.300218,1.891947,0.618079,2.103162,0.802711,5.195847,1.650925,0.883008,0.342791,0.245011
Frozen potato wedges,0.664775,0.480020,3.096824,4.353587,1.688861,1.216301,7.897629,9.015120,0.761179,0.548091,0.401046
Frozen sweet potato fries,0.409885,0.281673,2.641979,0.694194,1.967662,1.362967,12.579391,3.335497,0.469325,0.321617,0.342142
Lemons,0.470153,1.101691,4.813572,18.599275,0.611375,1.480950,6.255151,24.007351,0.538333,1.257922,0.623369
Limes,0.463008,1.420994,5.020169,18.861549,0.626187,1.998480,6.820544,25.442105,0.530152,1.622505,0.650124
Nut loaf,0.716131,0.495529,2.246645,0.820028,2.004030,1.385892,6.289355,2.291662,0.819982,0.565800,0.290946
Oat milk,0.453281,1.051135,6.718169,4.098738,0.526874,1.221709,7.813359,4.767600,0.519014,1.200196,0.870019
Onions,0.362860,1.014035,3.192865,12.702158,0.395357,1.089143,3.225629,13.388255,0.415481,1.157836,0.413483
Orange juice,0.488848,1.198713,9.279817,22.951580,0.705297,1.706871,12.984564,31.978453,0.559740,1.368702,1.201758
Oranges,0.466550,1.076517,4.971439,21.609950,0.666498,1.486787,6.945259,31.584671,0.534207,1.229178,0.643813
Pitta bread,0.563561,0.254204,0.745270,6.044426,1.804066,0.805656,2.328243,19.381761,0.645287,0.290253,0.096514
Potatoes,0.207276,0.232124,1.157598,7.651273,0.804449,0.952186,4.672538,36.574749,0.237335,0.265042,0.149912
Sourdough bread,0.851167,0.344747,1.242905,4.523647,2.371923,0.969474,3.681614,13.151977,0.974601,0.393636,0.160959

In [42]:
doublecond = data[(data['Bananas index (kg)'] > 5
) &
(data['Bananas index (100g protein)'] < 1
)].copy()

doublecond.sort_values('Bananas index (kg)', ascending = False)

,emissions_kg,emissions_1000kcal,emissions_100g_protein,emissions_100g_fat,land_use_kg,land_use_1000kcal,Land use per 100 grams of protein,Land use per 100 grams of fat,Bananas index (kg),Bananas index (1000 kcalories),Bananas index (100g protein)
entity,,,,,,,,,,,
Halloumi cheese,16.172452,5.282519,7.035951,7.141841,19.101111,6.247765,8.302601,8.456865,18.517731,6.031632,0.911172
Mackerel,13.606385,6.250301,7.133691,11.290381,5.801549,2.617001,3.054948,4.667267,15.579540,7.136655,0.923830
Tuna,13.075355,9.969608,4.972586,105.113632,5.521840,4.194251,2.167108,44.058029,14.971502,11.383397,0.643961
Pork chops,12.163891,4.588105,7.407893,5.900807,17.308312,6.422918,10.650062,8.198401,13.927860,5.238743,0.959339
Cod,10.904109,8.560719,7.087446,74.485781,5.267857,3.974725,3.518976,32.139084,12.485389,9.774713,0.917841
Salmon,10.412581,5.953093,4.832165,13.164939,4.747958,2.707115,2.214772,5.940113,11.922582,6.797300,0.625777
Chicken thighs,9.981881,5.095227,5.344501,7.672648,9.851754,5.023467,5.270620,7.568749,11.429423,5.817780,0.692125
Pork sausages,9.767878,3.660900,6.913241,5.448153,13.559548,5.112492,9.581818,7.713947,11.184385,4.180051,0.895281
Chicken wings,9.583456,4.650311,5.105153,6.969777,9.506970,4.613541,5.063860,6.938755,10.973219,5.309770,0.661129
Cod fish fingers,9.313182,4.701090,6.949603,11.205453,5.416458,2.706016,4.075833,6.432551,10.663750,5.367751,0.899990
Chicken breast,9.272323,5.830486,4.518434,27.716290,9.220959,5.796039,4.493710,27.518737,10.616967,6.657307,0.585148
Chicken sausages,8.164302,4.020155,5.400881,6.917650,8.330555,4.074470,5.523113,6.976656,9.348264,4.590252,0.699427
Cod fishcakes,7.815675,5.021886,6.541612,12.267606,3.808558,2.383748,3.272294,5.796482,8.949080,5.734039,0.847154
Chicken burger,5.434487,2.329615,3.661770,4.582128,6.053407,2.560246,4.219893,5.090691,6.222579,2.659977,0.474208
Olive oil,5.184628,0.591959,NaN,0.523292,21.707958,2.478318,NaN,2.190833,5.936487,0.675905,0.000000
Eggs,4.436600,2.765086,3.143945,3.959905,6.824729,4.365401,5.072666,6.293576,5.079982,3.157203,0.407148