# Day 3: Session 3B - The Filter Pattern

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/3b_filtering_data.html)

Date: 09/02/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)
goleta.shape

(1962, 15)

In [6]:
goleta[goleta['value'] > 20] # this is filtering everything that has a number > 20 in the value column

badvalues = goleta[goleta['value'] < 0]   # these are all the rows that have a value <0, which makes no sense hwo do you have negative concentration
badvalues

ozone = goleta[goleta['parameter'] == 'o3'] # this gives us all the rows that are measuring o3 or ozone
ozone.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [ ]:
goleta[goleta['parameter'] == 'pm25']['value'].describe()
# the above filters the df for columns where paremeter is pm25, then describes the 'value' column 

#pm25 analysis below, also filtering out values under 9
pm25anal = goleta[(goleta['parameter'] == 'pm25') & (goleta['value'] > 9)]
pm25anal.describe()

,location_id,value,latitude,longitude,country_iso,isMobile,isMonitor
count,128.0,128.000000,1.280000e+02,1.280000e+02,0.0,0.0,0.0
mean,1186.0,12.304688,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
std,0.0,2.678461,1.426669e-14,2.853339e-14,NaN,NaN,NaN
min,1186.0,10.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
25%,1186.0,10.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
50%,1186.0,11.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
75%,1186.0,14.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
max,1186.0,22.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN

In [ ]:
# using a ~ to turn a condition around (same as !=)

not_ozone = goleta[~(goleta['parameter'] == 'o3')]

# the above returns all rows where paremeter is NOT o3

# same as this

goleta[goleta['parameter'] != 'o3'].shape

In [ ]:
# using .isin to filter a littler easier

particulates = goleta[goleta['parameter'].isin(['pm25', 'pm10'])]
particulates

# the above filters goleta by all rows that have pm25 or pm10 in the parameter column

# can do the above with a list which is nice and easy

particulateswecareabout = ['pm25','pm10','o3']
goleta[goleta['parameter'].isin(particulateswecareabout)]

particulates.columns

particulates[['unit', 'value']] # need double backets for some reason?

       unit  value
711   µg/m³   20.0
712   µg/m³   13.0
713   µg/m³   12.0
714   µg/m³    9.0
715   µg/m³    8.0
...     ...    ...
1957  µg/m³   10.0
1958  µg/m³    8.0
1959  µg/m³    8.0
1960  µg/m³    9.0
1961  µg/m³    5.0

[1251 rows x 2 columns]

In [ ]:
#using the .copy thing to store data

o3df = goleta[goleta['parameter'] == 'o3'].copy()

goleta['value'].max()
goleta[goleta['value'] == goleta['value'].max()] # this is how you find a row with a specific value, like the max value in df

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1086,1186,Goleta,pm10,40.0,µg/m³,2024-08-06T00:00:00+00:00,2024-08-05T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow