## Ranking questions
jacob and rachel and oli

In [1]:
import pandas as pd
url = 'https://eds-217-essential-python.github.io/data/national_parks.csv'
df = pd.read_csv(url)

In [2]:
sum(df['unit_type'] == 'National Park')

sum(df['year'] == 'Total')

by_year = df[~ (df['year']=='Total')]

by_year.shape[0]

df.shape[0] - by_year.shape[0]

codeswelike = ['PW','IM','AK']
sum(by_year['region'].isin(codeswelike))

by_year[(by_year['unit_type'] == 'National Park') & (by_year['visitors'] > 5000000)]

,year,gnis_id,geometry,metadata,number_of_records,parkname,region,state,unit_code,unit_name,unit_type,visitors
794,2016,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,11312786.0
1033,2016,23866,POLYGON,http://nrdata.nps.gov/programs/Lands/GRCA_META...,1,Grand Canyon,IM,AZ,GRCA,Grand Canyon National Park,National Park,5969811.0
1087,2016,255923,POLYGON,http://nrdata.nps.gov/programs/Lands/YOSE_META...,1,Yosemite,PW,CA,YOSE,Yosemite National Park,National Park,5028868.0
1172,2015,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,10712674.0
1410,2015,23866,POLYGON,http://nrdata.nps.gov/programs/Lands/GRCA_META...,1,Grand Canyon,IM,AZ,GRCA,Grand Canyon National Park,National Park,5520736.0
1548,2014,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,10099276.0
1924,2013,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9354695.0
2297,2012,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9685829.0
2670,2011,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9008830.0
3039,2010,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9463538.0
3405,2009,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9491437.0
3771,2008,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9044010.0
4137,2007,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9372253.0
4502,2006,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9289215.0
4865,2005,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9192477.0
5228,2004,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9167046.0
5585,2003,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9366845.0
5938,2002,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9316420.0
6289,2001,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9197697.0
6639,2000,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,10175812.0
6988,1999,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,10283598.0
7337,1998,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9989395.0
7681,1997,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9965075.0
8021,1996,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9265667.0
8358,1995,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9080420.0
8693,1994,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8628174.0
9026,1993,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9283848.0
9358,1992,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8931690.0
9685,1991,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8654459.0
10007,1990,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8151769.0
10308,1989,578853,MULTIPOLYGON,NaN,1,NaN,NE,ME,ACAD,Acadia National Park,National Park,5440952.0
10326,1989,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8333553.0
10640,1988,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8770781.0
10952,1987,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,10209841.0
11263,1986,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9836306.0
11573,1985,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9319290.0
11876,1984,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8508390.0
12175,1983,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8435475.0
12468,1982,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8177869.0
12748,1981,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8312884.0
13022,1980,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8440953.0
13293,1979,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8019788.0
13558,1978,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8695534.0
13818,1977,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,9173600.0
14076,1976,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8991500.0
14330,1975,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8541500.0
14581,1974,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,7807800.0
14829,1973,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,7586300.0
15064,1972,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,8034753.0
15290,1971,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,7173000.0
15510,1970,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,6778500.0
15723,1969,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,6331100.0
15930,1968,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,6667100.0
16127,1967,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,6710100.0
16318,1966,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,6466100.0
16504,1965,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,5954900.0
16687,1964,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,5321100.0
16861,1963,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,5258700.0
17034,1962,1018241,MULTIPOLYGON,NaN,1,NaN,SE,NC,GRSM,Great Smoky Mountains National Park,National Park,5209800.0

how many have national parks as unit type 4743

how many year = total 386

by_years has 21174 rows

by_years with region filter has 9894 rows

59 rows, each row is a year that a national park had over 5milly visitors

In [3]:
by_year.sort_values('visitors', ascending = False).head(10)

,year,gnis_id,geometry,metadata,number_of_records,parkname,region,state,unit_code,unit_name,unit_type,visitors
11164,1987,255952,MULTIPOLYGON,http://nrdata.nps.gov/programs/Lands/GOGA_meta...,1,Golden Gate,PW,CA,GOGA,Golden Gate National Recreation Area,National Recreation Area,21767176.0
10853,1988,255952,MULTIPOLYGON,http://nrdata.nps.gov/programs/Lands/GOGA_meta...,1,Golden Gate,PW,CA,GOGA,Golden Gate National Recreation Area,National Recreation Area,21759271.0
11475,1986,255952,MULTIPOLYGON,http://nrdata.nps.gov/programs/Lands/GOGA_meta...,1,Golden Gate,PW,CA,GOGA,Golden Gate National Recreation Area,National Recreation Area,21582368.0
5923,2002,1009494,MULTIPOLYGON,NaN,1,NaN,NT,NC,BLRI,Blue Ridge Parkway,Parkway,21538760.0
12942,1981,255952,MULTIPOLYGON,http://nrdata.nps.gov/programs/Lands/GOGA_meta...,1,Golden Gate,PW,CA,GOGA,Golden Gate National Recreation Area,National Recreation Area,20279789.0
10628,1988,1009494,MULTIPOLYGON,NaN,1,NaN,NT,NC,BLRI,Blue Ridge Parkway,Parkway,20002975.0
6274,2001,1009494,MULTIPOLYGON,NaN,1,NaN,NT,NC,BLRI,Blue Ridge Parkway,Parkway,19969587.0
12666,1982,255952,MULTIPOLYGON,http://nrdata.nps.gov/programs/Lands/GOGA_meta...,1,Golden Gate,PW,CA,GOGA,Golden Gate National Recreation Area,National Recreation Area,19897389.0
6973,1999,1009494,MULTIPOLYGON,NaN,1,NaN,NT,NC,BLRI,Blue Ridge Parkway,Parkway,19836842.0
6624,2000,1009494,MULTIPOLYGON,NaN,1,NaN,NT,NC,BLRI,Blue Ridge Parkway,Parkway,19153081.0

In [4]:
sixteen = by_year[by_year['year'] == '2016']

In [13]:
np_2016 = sixteen.sort_values('visitors', ascending = False)[['unit_name', 'state', 'visitors']]

In [6]:
print(np_2016.shape)

(10, 3)

In [7]:
sum(np_2016['visitors'] > 1000000)

10

In [9]:
max_visit = np_2016['visitors'].idxmax()
by_year.loc[max_visit, 'unit_name']

'Golden Gate National Recreation Area'

In [21]:
codeswelove = ['CA', 'UT', 'AZ']
np_2016 = np_2016[np_2016['state'].isin(codeswelove)]

np_2016['state'].value_counts()
np_2016.sort_values('visitors', ascending= False)

                                              unit_name state    visitors
1055               Golden Gate National Recreation Area    CA  15638777.0
1033                         Grand Canyon National Park    AZ   5969811.0
1087                             Yosemite National Park    CA   5028868.0
1006    San Francisco Maritime National Historical Park    CA   4334752.0
981                                  Zion National Park    UT   4295127.0
1086               Glen Canyon National Recreation Area    UT   3239525.0
1009                          Joshua Tree National Park    CA   2505286.0
837                       Point Reyes National Seashore    CA   2438442.0
873                          Bryce Canyon National Park    UT   2365110.0
910                   Fort Point National Historic Site    CA   2264154.0
848                                Arches National Park    UT   1585718.0
1028                         Death Valley National Park    CA   1296283.0
892                               Sequoia National Park    CA   1254688.0
988                        Muir Woods National Monument    CA   1123121.0
1003                         Capitol Reef National Park    UT   1064904.0
887                          Cabrillo National Monument    CA    959145.0
772     Santa Monica Mountains National Recreation Area    CA    906606.0
846                      Cedar Breaks National Monument    UT    899676.0
909   Whiskeytown-Shasta-Trinity National Recreation...    CA    875565.0
1074                 Canyon de Chelly National Monument    AZ    821406.0
1100                              Saguaro National Park    AZ    820426.0
918                           Canyonlands National Park    UT    776218.0
1026                     Petrified Forest National Park    AZ    643274.0
973                          Kings Canyon National Park    CA    607479.0
1143                           Mojave National Preserve    CA    585635.0
804                               Redwood National Park    CA    536297.0
1064                      Lassen Volcanic National Park    CA    536068.0
972                  Montezuma Castle National Monument    AZ    392168.0
917                       Channel Islands National Park    CA    364807.0
865                 Organ Pipe Cactus National Monument    AZ    234186.0
833                           Wupatki National Monument    AZ    223172.0
1023                            Pinnacles National Park    CA    215555.0
938                     Walnut Canyon National Monument    AZ    152444.0
960                          Coronado National Memorial    AZ    136075.0
1005                  Devils Postpile National Monument    CA    135404.0
966                         Lava Beds National Monument    CA    127699.0
871                     Manzanar National Historic Site    CA    105307.0
822                          Tuzigoot National Monument    AZ    104604.0
935                   Natural Bridges National Monument    UT    101843.0
828                   Timpanogos Cave National Monument    UT     91261.0
934                    Rainbow Bridge National Monument    UT     86369.0
1037                Casa Grande Ruins National Monument    AZ     75752.0
879         Hubbell Trading Post National Historic Site    AZ     67276.0
903                            Navajo National Monument    AZ     65705.0
926   Rosie the Riveter/World War II Home Front Nati...    CA     64425.0
849             Sunset Crater Volcano National Monument    AZ     60233.0
963                 Golden Spike National Historic Site    UT     60027.0
1045                       Chiricahua National Monument    AZ     51277.0
949                    John Muir National Historic Site    CA     49376.0
855                       Pipe Spring National Monument    AZ     46710.0
821                 Tumacacori National Historical Park    AZ     43829.0
863                         Hovenweep National Monument    UT     42862.0
841                             Tonto National Monument    AZ     38048.0
1019                  Casar E. Chpvez National Monument    CA     17216.0
818                   Fort Bowie National Historic Site    AZ      8013.0
901               Eugene O'Neill National Historic Site    CA      4287.0
1056      Port Chicago Naval Magazine National Memorial    CA      1942.0

california   most park
ggp top park

Need to know : number of visitors, do they mean total or by year?
In 2016 the busiest park in California was Golden Gate National Park