# Day 3: Session 3C - The Top-N Pattern

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/3c_sorting_and_ranking.html)

Date: 09/02/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)

pm25 = goleta[goleta['parameter'] == 'pm25'].copy()
pm25.shape

(734, 15)

In [5]:
pm25.sort_values('value').head() # default it sorts smallest to largest

pm25.sort_values('value', ascending=False).head() # this is how you make it go from largest to smallest

pm25.sort_values('parameter', ascending=False).head() # can even sort by strings

pm25.sort_values('datetimeUtc', ascending=False).head(10) # can even sort by strings

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1961,1186,Goleta,pm25,5.0,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1960,1186,Goleta,pm25,9.0,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1959,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1958,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1957,1186,Goleta,pm25,10.0,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1956,1186,Goleta,pm25,14.0,µg/m³,2024-08-11T19:00:00+00:00,2024-08-11T12:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1955,1186,Goleta,pm25,13.0,µg/m³,2024-08-11T18:00:00+00:00,2024-08-11T11:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1954,1186,Goleta,pm25,16.0,µg/m³,2024-08-11T17:00:00+00:00,2024-08-11T10:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1953,1186,Goleta,pm25,16.0,µg/m³,2024-08-11T16:00:00+00:00,2024-08-11T09:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1952,1186,Goleta,pm25,10.0,µg/m³,2024-08-11T15:00:00+00:00,2024-08-11T08:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [ ]:
# the top-N pattern is the following code
# df.sort_values('column', ascending=False).head(n)

# you can even choose which columns you want if you index at the end of the code

pm25.sort_values('value', ascending=False).head(10)[['datetimeLocal', 'value', 'unit']]

# double brackets is necessary [[]]

# you can filter, then sort in that order

goleta[goleta['parameter'] == 'pm10'].sort_values('value', ascending=False).head(5)[
    ['datetimeLocal', 'value', 'unit']
]

                  datetimeLocal  value   unit
1376  2024-07-18T01:00:00-07:00   22.0  µg/m³
1712  2024-08-01T01:00:00-07:00   22.0  µg/m³
1873  2024-08-08T01:00:00-07:00   21.0  µg/m³
1930  2024-08-10T10:00:00-07:00   20.0  µg/m³
1838  2024-08-06T13:00:00-07:00   19.0  µg/m³
1863  2024-08-07T15:00:00-07:00   19.0  µg/m³
1534  2024-07-24T15:00:00-07:00   17.0  µg/m³
1592  2024-07-27T01:00:00-07:00   17.0  µg/m³
1839  2024-08-06T14:00:00-07:00   16.0  µg/m³
1954  2024-08-11T10:00:00-07:00   16.0  µg/m³

In [11]:
# you can get the row # of a max using the following code

worsthour = pm25['value'].idxmax()

# that returns the row index, then you could use that to find a specfic cell

pm25.loc[worsthour,'datetimeLocal']

pm25['value'].max()
pm25[pm25['value'] == pm25['value'].max()]

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1376,1186,Goleta,pm25,22.0,µg/m³,2024-07-18T08:00:00+00:00,2024-07-18T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1712,1186,Goleta,pm25,22.0,µg/m³,2024-08-01T08:00:00+00:00,2024-08-01T01:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow