# Day 2 EOD: A Data Biography of Toolik Field Station Weather

Date: 09/01/2026

In [4]:
import pandas as pd
data = pd.read_csv('https://eds-217-essential-python.github.io/data/toolik_weather.csv')

The df has 11171 rows and 21 columns
column names are listed below
data typpes are listed below
beginning of data set is 19880601
end of data set is 20181231

In [11]:
data
list(data.columns)
data.dtypes
data['Date'].min()
data['Date'].max()

20181231

all columns other than the first 5 have null values somewhere inside them

flag daily windspeed, flag global rad, and flag air temp have the most null values

flag daily winspeed is missing all values except 1

flag columns might be summary statistics like means and sums

In [15]:
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11171 entries, 0 to 11170
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Year                             11171 non-null  int64
 1   Month                            11171 non-null  int64
 2   Date                             11171 non-null  int64
 3   LTER_Site                        11171 non-null  object
 4   Station                          11171 non-null  object
 5   Daily_AirTemp_Mean_C             11171 non-null  float64
 6   Flag_Daily_AirTemp_Mean_C        1310 non-null   object
 7   Daily_AirTemp_AbsMax_C           11001 non-null  float64
 8   Flag_Daily_AirTemp_AbsMax_C      1020 non-null   object
 9   Daily_AirTemp_AbsMin_C           10967 non-null  float64
 10  Flag_Daily_AirTemp_AbsMin_C      1236 non-null   object
 11  Daily_Precip_Total_mm            10751 non-null  float64
 12  Flag_Daily_Precip_Total_mm       3169 non-null   object
 13  Daily_windsp_mean_msec           10345 non-null  float64
 14  FLAG_Daily_windsp_mean_msec      1 non-null      object
 15  Daily_Windspeed_AbsMax_m_s       10325 non-null  float64
 16  Daily_globalrad_total_jcm2       4118 non-null   float64
 17  FLAG_Daily_globalrad_total_mjm2  15 non-null     object
 18  Moss                             10333 non-null  float64
 19  Soil20cm                         10351 non-null  float64
 20  Comments                         8924 non-null   object
dtypes: float64(9), int64(3), object(9)
memory usage: 1.8+ MB

Year                                   0
Month                                  0
Date                                   0
LTER_Site                              0
Station                                0
Daily_AirTemp_Mean_C                   0
Flag_Daily_AirTemp_Mean_C           9861
Daily_AirTemp_AbsMax_C               170
Flag_Daily_AirTemp_AbsMax_C        10151
Daily_AirTemp_AbsMin_C               204
Flag_Daily_AirTemp_AbsMin_C         9935
Daily_Precip_Total_mm                420
Flag_Daily_Precip_Total_mm          8002
Daily_windsp_mean_msec               826
FLAG_Daily_windsp_mean_msec        11170
Daily_Windspeed_AbsMax_m_s           846
Daily_globalrad_total_jcm2          7053
FLAG_Daily_globalrad_total_mjm2    11156
Moss                                 838
Soil20cm                             820
Comments                            2247
dtype: int64

There is only one site and one station in this data set: Arc and Tlkmain.

There is only one value in the flag_daily_airtemp_mean_C column, and it's E.

Most years have data for every day of the year, but some have 1 extra and 1 has only ~half a year

In [27]:
data['LTER_Site'].value_counts()
data['Station'].value_counts()
data['Flag_Daily_AirTemp_Mean_C'].value_counts()
data['Year'].unique()
data['Year'].value_counts().tail()

Year
2011    365
2017    365
2015    365
2018    365
1988    214
Name: count, dtype: int64

mean daily air temp: -8.2C
    min: -55.60
    max: 20.70
    seems like a normal range of temps to me but i never been there

Daily precip mean: 0.95
    min:0
    max:64.5
    eh looks mostly fine to me

In [29]:
data.describe()

,Year,Month,Date,Daily_AirTemp_Mean_C,Daily_AirTemp_AbsMax_C,Daily_AirTemp_AbsMin_C,Daily_Precip_Total_mm,Daily_windsp_mean_msec,Daily_Windspeed_AbsMax_m_s,Daily_globalrad_total_jcm2,Moss,Soil20cm
count,11171.000000,11171.000000,1.117100e+04,11171.000000,11001.000000,10967.000000,10751.000000,10345.000000,10325.000000,4118.000000,10333.000000,10351.000000
mean,2003.203384,6.570674,2.003271e+07,-8.196437,-3.447132,-13.295924,0.950953,2.995592,6.321288,1324.307188,-1.471402,-2.055647
std,8.831548,3.443637,8.830795e+04,14.831314,14.805298,14.727318,2.749060,1.553574,2.878432,866.670139,7.354649,5.555551
min,1988.000000,1.000000,1.988060e+07,-55.600000,-53.600000,-57.600000,0.000000,0.000000,0.000000,-2.000000,-24.000000,-21.000000
25%,1996.000000,4.000000,1.996012e+07,-19.700000,-14.200000,-25.600000,0.000000,2.000000,4.300000,591.000000,-7.000000,-6.000000
50%,2003.000000,7.000000,2.003092e+07,-7.100000,-2.900000,-12.300000,0.000000,2.800000,5.900000,1268.000000,-2.000000,-1.000000
75%,2011.000000,10.000000,2.011051e+07,4.400000,8.900000,-0.100000,0.400000,3.600000,7.800000,2026.000000,4.000000,2.000000
max,2018.000000,12.000000,2.018123e+07,20.700000,28.200000,14.900000,64.500000,12.500000,27.000000,3205.000000,19.000000,11.000000

In [39]:
data.columns
keep = ['Year','Date','Daily_AirTemp_AbsMin_C','Flag_Daily_AirTemp_AbsMin_C','Station']
newdata = data[keep]
dict = {'Year':'yea','Date':'dat'}
newdatarename = newdata.rename(columns=dict)
newdatarename

,yea,dat,Daily_AirTemp_AbsMin_C,Flag_Daily_AirTemp_AbsMin_C,Station
0,1988,19880601,NaN,NaN,TLKMAIN
1,1988,19880602,NaN,NaN,TLKMAIN
2,1988,19880603,NaN,NaN,TLKMAIN
3,1988,19880604,NaN,NaN,TLKMAIN
4,1988,19880605,NaN,NaN,TLKMAIN
...,...,...,...,...,...
11166,2018,20181227,-26.7,NaN,TLKMAIN
11167,2018,20181228,-26.3,NaN,TLKMAIN
11168,2018,20181229,-25.8,NaN,TLKMAIN
11169,2018,20181230,-28.0,NaN,TLKMAIN
11170,2018,20181231,-7.9,NaN,TLKMAIN

The data set is a bunch of measurements from online from a station named tulik or something and, for the most part, they are taking data once a day every day of the year from 1988 to another date.

There are something like 11171 rows and something like 15 cols.

The condition is basically good, things look nice not lots of null values except for in the flag columns but that might be by design. Two things people should know is that for some years there are 366 data poitns and the flag columsn are mostly unpopulated. 

Yes i think you could use it to talk about changing summer temps but you would have to filter out some data and double check that there arent any sneaky weird numbers in there.